/*
 * Soulbrou native runtime public interface.
 *
 * This header is shared by three consumers:
 *   - the runtime library itself (libsoulbrou.so injected into target APKs),
 *   - the C code generated by the dex2c engine in compile mode,
 *   - the host unit tests of the protection logic.
 *
 * All generated code operates on the SB register union so translated and
 * interpreted methods share identical semantics.
 *
 * Copyright 2025-2026 beto2-dev
 * Licensed under the Apache License, Version 2.0.
 */
#ifndef SOULBROU_RUNTIME_H
#define SOULBROU_RUNTIME_H

#include <jni.h>
#include <setjmp.h>
#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/* Register file                                                       */
/* ------------------------------------------------------------------ */

typedef union SB {
    jint i;
    jlong j;
    jfloat f;
    jdouble d;
    jobject o;
} SB;

#define SB_I(x) ((SB){.i = (jint)(x)})
#define SB_J(x) ((SB){.j = (jlong)(x)})
#define SB_F(x) ((SB){.f = (jfloat)(x)})
#define SB_D(x) ((SB){.d = (jdouble)(x)})
#define SB_O(x) ((SB){.o = (jobject)(x)})

static inline jint sb_to_int(SB v) { return v.i; }
static inline jlong sb_to_long(SB v) { return v.j; }
static inline jfloat sb_to_float(SB v) { return v.f; }
static inline jdouble sb_to_double(SB v) { return v.d; }
static inline jobject sb_to_obj(SB v) { return v.o; }

/* ------------------------------------------------------------------ */
/* Try frames                                                          */
/* ------------------------------------------------------------------ */

typedef struct sb_frame {
    jmp_buf buf;
    struct sb_frame *next;
    int active;
} sb_frame;

int sb_try_enter(sb_frame *frame);
void sb_try_exit(sb_frame *frame);
void sb_try_exit_frame(void);
sb_frame *sb_frame_push(void);
void sb_try_unwind(int keep_depth);
void sb_propagate(JNIEnv *env);
jint sb_try_depth(void);

/* ------------------------------------------------------------------ */
/* Object model operations                                             */
/* ------------------------------------------------------------------ */

jobject sb_new_string(JNIEnv *env, const char *utf8);
jobject sb_const_class(JNIEnv *env, const char *descriptor);
jobject sb_new_instance(JNIEnv *env, const char *descriptor);
jobject sb_check_cast(JNIEnv *env, jobject obj, const char *descriptor);
jint sb_instance_of(JNIEnv *env, jobject obj, const char *descriptor);
jint sb_array_length(JNIEnv *env, jobject array);
jobject sb_new_array(JNIEnv *env, jint length, char kind);
SB sb_aget(JNIEnv *env, jobject array, jint index, char kind);
void sb_aput(JNIEnv *env, jobject array, jint index, char kind, SB value);
jobject sb_filled_new_array(JNIEnv *env, const char *descriptor, SB *values, jint count, char kind);
void sb_fill_array_data(JNIEnv *env, jobject array, const unsigned char *data, jint length, jint width);
void sb_monitor(JNIEnv *env, jobject obj, int enter);
void sb_throw(JNIEnv *env, jobject exception);
jobject sb_move_exception(JNIEnv *env);
jobject sb_exception(JNIEnv *env);
int sb_is_a(JNIEnv *env, jobject exception, const char *descriptor);
void sb_throw_pending(JNIEnv *env);

SB sb_iget(JNIEnv *env, jobject obj, const char *class_desc, const char *name, const char *type);
void sb_iput(JNIEnv *env, jobject obj, const char *class_desc, const char *name, const char *type, SB value);
SB sb_sget(JNIEnv *env, const char *class_desc, const char *name, const char *type);
void sb_sput(JNIEnv *env, const char *class_desc, const char *name, const char *type, SB value);

typedef enum SB_INVOKE_KIND {
    SB_INVOKE_NONE = 0,
    SB_INVOKE_VIRTUAL = 1,
    SB_INVOKE_SUPER = 2,
    SB_INVOKE_DIRECT = 3,
    SB_INVOKE_STATIC = 4,
    SB_INVOKE_INTERFACE = 5
} SB_INVOKE_KIND;

SB sb_invoke(JNIEnv *env, int kind, jobject receiver, const char *class_desc,
             const char *name, const char *signature, char ret_kind, jvalue *args);

/* Arithmetic helpers implementing Java edge case semantics. */
jint sb_add_i(jint a, jint b);
jint sb_sub_i(jint a, jint b);
jint sb_mul_i(jint a, jint b);
jint sb_div_i(JNIEnv *env, jint a, jint b);
jint sb_rem_i(JNIEnv *env, jint a, jint b);
jint sb_and_i(jint a, jint b);
jint sb_or_i(jint a, jint b);
jint sb_xor_i(jint a, jint b);
jint sb_shl_i(jint a, jint b);
jint sb_shr_i(jint a, jint b);
jint sb_ushr_i(jint a, jint b);
jlong sb_add_l(jlong a, jlong b);
jlong sb_sub_l(jlong a, jlong b);
jlong sb_mul_l(jlong a, jlong b);
jlong sb_div_l(JNIEnv *env, jlong a, jlong b);
jlong sb_rem_l(JNIEnv *env, jlong a, jlong b);
jlong sb_and_l(jlong a, jlong b);
jlong sb_or_l(jlong a, jlong b);
jlong sb_xor_l(jlong a, jlong b);
jlong sb_shl_l(jlong a, jlong b);
jlong sb_shr_l(jlong a, jlong b);
jlong sb_ushr_l(jlong a, jlong b);
jfloat sb_add_f(jfloat a, jfloat b);
jfloat sb_sub_f(jfloat a, jfloat b);
jfloat sb_mul_f(jfloat a, jfloat b);
jfloat sb_div_f(jfloat a, jfloat b);
jfloat sb_rem_f(jfloat a, jfloat b);
jdouble sb_add_d(jdouble a, jdouble b);
jdouble sb_sub_d(jdouble a, jdouble b);
jdouble sb_mul_d(jdouble a, jdouble b);
jdouble sb_div_d(jdouble a, jdouble b);
jdouble sb_rem_d(jdouble a, jdouble b);
jint sb_cmpl_float(jfloat a, jfloat b);
jint sb_cmpg_float(jfloat a, jfloat b);
jint sb_cmpl_double(jdouble a, jdouble b);
jint sb_cmpg_double(jdouble a, jdouble b);
jfloat sb_l2f(jlong a);
jint sb_f2i(jfloat a);
jlong sb_f2l(jfloat a);
jint sb_d2i(jdouble a);
jlong sb_d2l(jdouble a);

jobject sb_box(JNIEnv *env, SB value, char kind);
SB sb_unbox(JNIEnv *env, jobject box, char kind);

/* ------------------------------------------------------------------ */
/* Protection checks                                                   */
/* ------------------------------------------------------------------ */

typedef enum SB_PROTECTION {
    SB_PROT_NONE = 0,
    SB_PROT_ANTI_ROOT = 1,
    SB_PROT_ANTI_FRIDA = 2,
    SB_PROT_ANTI_DEXDUMP = 3,
    SB_PROT_ANTI_TAMPERING = 4,
    SB_PROT_SIGNATURE_CHECK = 5,
    SB_PROT_ANTI_DEBUG = 6,
    SB_PROT_ANTI_EMULATOR = 7,
    SB_PROT_COUNT = 8
} SB_PROTECTION;

int sb_check_anti_root(void);
int sb_check_anti_frida(void);
int sb_check_anti_dexdump(void);
int sb_check_anti_tampering(JNIEnv *env);
int sb_check_signature(JNIEnv *env);
int sb_check_anti_debug(void);
int sb_check_anti_emulator(void);

/* Advances the chained verification state, called by every dispatch. */
void sb_chain_step(JNIEnv *env);
/* Resets chain state (first call of a session). */
void sb_chain_init(void);

/* Configures which protections run; bits of SB_PROTECTION. */
void sb_configure_protections(uint32_t mask);
uint32_t sb_active_protections(void);

/* Integrity data blobs installed by the pipeline. */
void sb_install_expected(uint32_t dex_crc, const uint8_t *cert_sha256);

/* Version of the runtime library. */
const char *sb_runtime_version(void);

#ifdef __cplusplus
}
#endif

#endif /* SOULBROU_RUNTIME_H */
