package com.soulbrou.data

import android.content.Context
import java.io.File
import java.security.SecureRandom

/**
 * Stores the keystores generated by the application under its private
 * directory. Files never leave the device and are excluded from backups.
 */
class KeystoreRepository(context: Context) {

    private val directory = File(context.filesDir, "keystores").apply { mkdirs() }

    fun list(): List<File> = directory.listFiles()?.filter { it.isFile }?.sortedBy { it.name } ?: emptyList()

    fun save(displayName: String, bytes: ByteArray): File {
        val safeName = displayName.replace(Regex("[^A-Za-z0-9._-]"), "_")
        val file = File(directory, "$safeName.p12")
        var index = 1
        var target = file
        while (target.exists()) {
            target = File(directory, "${safeName}_$index.p12")
            index++
        }
        target.writeBytes(bytes)
        return target
    }

    fun read(file: File): ByteArray = file.readBytes()

    fun delete(file: File): Boolean = file.delete()

    companion object {
        /** Generates a strong password for new keystores. */
        fun randomPassword(length: Int = 20): String {
            val alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!#%+".toCharArray()
            val random = SecureRandom()
            return String(CharArray(length) { alphabet[random.nextInt(alphabet.size)] })
        }
    }
}
